import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { RefreshCw, Search, Pencil, Trash2, ExternalLink, Copy, Plus, CheckCircle2, AlertCircle } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { useToast } from "@/hooks/use-toast";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AdminSidebar } from "@/components/admin/AdminSidebar";

type Tier={min_quantity:number;max_quantity:number|null;unit_price:number};
type Product={id:string;name:string;whatsapp_retailer_id:string|null;whatsapp_catalog_id:string|null;whatsapp_sync_status:string|null};
type Mapping={whatsapp_retailer_id:string;product_id:string|null;product_name:string|null;amazon_url:string|null;amazon_price:number|null;meesho_url:string|null;meesho_price:number|null;whatsapp_url:string|null;whatsapp_price:number|null;whatsapp_enabled:boolean;cod_enabled:boolean;wholesale_enabled:boolean;wholesale_pricing:Tier[];enabled:boolean};
type Form={whatsapp_retailer_id:string;product_id:string;product_name:string;amazon_url:string;amazon_price:string;meesho_url:string;meesho_price:string;whatsapp_url:string;whatsapp_price:string;whatsapp_enabled:boolean;cod_enabled:boolean;wholesale_enabled:boolean;wholesale_pricing:Tier[];enabled:boolean};
const empty:Form={whatsapp_retailer_id:"",product_id:"",product_name:"",amazon_url:"",amazon_price:"",meesho_url:"",meesho_price:"",whatsapp_url:"",whatsapp_price:"",whatsapp_enabled:true,cod_enabled:true,wholesale_enabled:false,wholesale_pricing:[],enabled:true};
const validUrl=(v:string)=>{if(!v.trim())return true;try{return new URL(v.trim()).protocol==="https:";}catch{return false;}};

export default function AdminMarketplaceCatalogConfigV2(){
 const{toast}=useToast();const qc=useQueryClient();const[search,setSearch]=useState("");const[form,setForm]=useState<Form>(empty);const[editing,setEditing]=useState<Mapping|null>(null);const[codCharge,setCodCharge]=useState("20");
 const{data:products=[],isLoading:loading}=useQuery<Product[]>({queryKey:["marketplace-catalog-products"],queryFn:async()=>{const{data,error}=await supabase.from("products" as any).select("id,name,whatsapp_retailer_id,whatsapp_catalog_id,whatsapp_sync_status").order("name");if(error)throw error;return(data||[]) as Product[];}});
 const{data:mappings=[],isLoading:mloading}=useQuery<Mapping[]>({queryKey:["shoppinghub-marketplace-mappings"],queryFn:async()=>{const{data,error}=await supabase.from("shoppinghub_marketplace_map" as any).select("*").order("product_name");if(error)throw error;return(data||[]) as Mapping[];}});
 const{data:setting}=useQuery<{numeric_value:number|null}|null>({queryKey:["shoppinghub-cod-charge"],queryFn:async()=>{const{data,error}=await(supabase.from("shoppinghub_order_settings" as any) as any).select("numeric_value").eq("setting_key","cod_charge").maybeSingle();if(error)throw error;return data||null;}});
 const actualCod=setting?.numeric_value??Number(codCharge||20);
 const sync=useMutation({mutationFn:async()=>{const{data,error}=await supabase.functions.invoke("sync-whatsapp-catalog",{body:{source:"marketplace-links"}});if(error)throw error;if(data?.error)throw new Error(data.error);return data;},onSuccess:d=>{qc.invalidateQueries({queryKey:["marketplace-catalog-products"]});qc.invalidateQueries({queryKey:["shoppinghub-marketplace-mappings"]});toast({title:"WhatsApp catalog refreshed",description:`${d?.synced??0} catalog products synchronized.`});},onError:(e:any)=>toast({title:"Catalog refresh failed",description:e.message,variant:"destructive"})});
 const byRetail=useMemo(()=>new Map(mappings.map(m=>[m.whatsapp_retailer_id,m])),[mappings]);const byProduct=useMemo(()=>new Map(mappings.filter(m=>m.product_id).map(m=>[String(m.product_id),m])),[mappings]);
 const getMap=(p:Product)=>p.whatsapp_retailer_id?byRetail.get(p.whatsapp_retailer_id)||byProduct.get(p.id):byProduct.get(p.id);
 const rows=products.filter(p=>{const q=search.toLowerCase().trim();return!q||[p.name,p.whatsapp_retailer_id,p.whatsapp_catalog_id].some(v=>String(v||"").toLowerCase().includes(q));});
 const edit=(p:Product,m?:Mapping)=>{setEditing(m||null);setForm(m?{whatsapp_retailer_id:m.whatsapp_retailer_id,product_id:m.product_id||p.id,product_name:m.product_name||p.name,amazon_url:m.amazon_url||"",amazon_price:m.amazon_price==null?"":String(m.amazon_price),meesho_url:m.meesho_url||"",meesho_price:m.meesho_price==null?"":String(m.meesho_price),whatsapp_url:m.whatsapp_url||"",whatsapp_price:m.whatsapp_price==null?"":String(m.whatsapp_price),whatsapp_enabled:m.whatsapp_enabled!==false,cod_enabled:m.cod_enabled!==false,wholesale_enabled:m.wholesale_enabled===true,wholesale_pricing:Array.isArray(m.wholesale_pricing)?m.wholesale_pricing:[],enabled:m.enabled!==false}:{...empty,product_id:p.id,product_name:p.name,whatsapp_retailer_id:p.whatsapp_retailer_id||""});window.scrollTo({top:0,behavior:"smooth"});};
 const choose=(id:string)=>{const p=products.find(x=>x.id===id);if(p)edit(p,getMap(p));else{setForm(empty);setEditing(null);}};
 const save=useMutation({mutationFn:async()=>{if(!form.product_id)throw new Error("Select a ShoppingHub product.");if(!form.whatsapp_retailer_id.trim())throw new Error("WhatsApp Catalog Product ID is required. Refresh the catalog or enter the retailer ID from Meta Catalog Manager.");const nums=[form.amazon_price,form.meesho_price,form.whatsapp_price].map(v=>v.trim()?Number(v):null);if(![form.amazon_url,form.meesho_url,form.whatsapp_url].every(validUrl))throw new Error("Marketplace links must be valid HTTPS URLs.");if(nums.some(v=>v!=null&&(!Number.isFinite(v)||v<=0)))throw new Error("Channel prices must be positive numbers.");if(form.wholesale_enabled&&!form.wholesale_pricing.length)throw new Error("Add at least one wholesale tier or disable wholesale.");const id=form.whatsapp_retailer_id.trim();const{error}=await supabase.from("shoppinghub_marketplace_map" as any).upsert({whatsapp_retailer_id:id,product_id:form.product_id,product_name:form.product_name,amazon_url:form.amazon_url||null,amazon_price:nums[0],meesho_url:form.meesho_url||null,meesho_price:nums[1],whatsapp_url:form.whatsapp_url||null,whatsapp_price:nums[2],whatsapp_enabled:form.whatsapp_enabled,cod_enabled:form.cod_enabled,wholesale_enabled:form.wholesale_enabled,wholesale_pricing:form.wholesale_pricing,enabled:form.enabled},{onConflict:"whatsapp_retailer_id"});if(error)throw error;const{error:pe}=await supabase.from("products" as any).update({whatsapp_retailer_id:id}).eq("id",form.product_id);if(pe)throw pe;},onSuccess:()=>{qc.invalidateQueries({queryKey:["shoppinghub-marketplace-mappings"]});qc.invalidateQueries({queryKey:["marketplace-catalog-products"]});setForm(empty);setEditing(null);toast({title:"Product configuration saved"});},onError:(e:any)=>toast({title:"Could not save mapping",description:e.message,variant:"destructive"})});
 const remove=useMutation({mutationFn:async(id:string)=>{const{error}=await supabase.from("shoppinghub_marketplace_map" as any).delete().eq("whatsapp_retailer_id",id);if(error)throw error;},onSuccess:()=>{qc.invalidateQueries({queryKey:["shoppinghub-marketplace-mappings"]});toast({title:"Mapping deleted"});}});
 const addTier=()=>setForm(f=>({...f,wholesale_pricing:[...f.wholesale_pricing,{min_quantity:1,max_quantity:null,unit_price:0}]}));
 const updateTier=(i:number,k:keyof Tier,v:string)=>setForm(f=>({...f,wholesale_pricing:f.wholesale_pricing.map((t,j)=>j===i?{...t,[k]:k==="max_quantity"&&!v.trim()?null:Number(v)}:t)}));
 return <SidebarProvider><div className="min-h-screen flex w-full bg-muted/30"><AdminSidebar activeTab="marketplace-links" onTabChange={()=>{}}/><div className="flex-1 min-w-0"><header className="h-14 flex items-center gap-4 border-b bg-background px-4 sticky top-0 z-40"><SidebarTrigger/><div><h2 className="font-semibold text-sm">Marketplace Links</h2><p className="text-xs text-muted-foreground">WhatsApp catalog → Amazon / Meesho / WhatsApp</p></div></header><main className="p-6"><div className="space-y-6 max-w-7xl mx-auto">
 <div className="flex flex-col gap-3 md:flex-row md:justify-between"><div><h1 className="text-2xl font-bold">Product Order Channels</h1><p className="text-muted-foreground">All ShoppingHub products are listed. Configure each product independently.</p></div><Button variant="outline" onClick={()=>sync.mutate()} disabled={sync.isPending}><RefreshCw className={`mr-2 h-4 w-4 ${sync.isPending?"animate-spin":""}`}/>{sync.isPending?"Syncing...":"Refresh WhatsApp Catalog"}</Button></div>
 <Card><CardHeader><CardTitle>Global COD Charge</CardTitle></CardHeader><CardContent className="flex items-end gap-3"><div><Label>COD Charge (₹)</Label><Input className="mt-2 w-40" type="number" value={setting?.numeric_value??codCharge} onChange={e=>setCodCharge(e.target.value)}/></div><span className="pb-2 text-sm text-muted-foreground">Current: ₹{Number(actualCod).toFixed(0)} added once per COD cart.</span></CardContent></Card>
 <Card><CardHeader><CardTitle>{editing?"Edit Product Configuration":"Configure Product"}</CardTitle></CardHeader><CardContent className="grid gap-4 md:grid-cols-2"><div className="md:col-span-2"><Label>Select Product</Label><select className="mt-2 h-11 w-full rounded-md border bg-background px-3 text-sm" value={form.product_id} onChange={e=>choose(e.target.value)}><option value="">Select a ShoppingHub product...</option>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><p className="mt-2 text-xs text-muted-foreground">All products are selectable even if WhatsApp sync is pending.</p></div><div className="md:col-span-2 rounded-md border bg-muted/30 p-3"><div className="font-medium">{form.product_name||"No product selected"}</div><div className="text-xs text-muted-foreground mt-1">WhatsApp retailer ID: {form.whatsapp_retailer_id||"Not synchronized"}</div></div><div className="md:col-span-2"><Label>WhatsApp Catalog Product ID</Label><Input className="mt-2" placeholder="e.g. w7ivha0s34" value={form.whatsapp_retailer_id} onChange={e=>setForm({...form,whatsapp_retailer_id:e.target.value})}/></div><div><Label>Amazon URL</Label><Input className="mt-2" value={form.amazon_url} onChange={e=>setForm({...form,amazon_url:e.target.value})}/></div><div><Label>Amazon Price (₹)</Label><Input className="mt-2" type="number" value={form.amazon_price} onChange={e=>setForm({...form,amazon_price:e.target.value})}/></div><div><Label>Meesho URL</Label><Input className="mt-2" value={form.meesho_url} onChange={e=>setForm({...form,meesho_url:e.target.value})}/></div><div><Label>Meesho Price (₹)</Label><Input className="mt-2" type="number" value={form.meesho_price} onChange={e=>setForm({...form,meesho_price:e.target.value})}/></div><div><Label>WhatsApp Price (₹)</Label><Input className="mt-2" type="number" value={form.whatsapp_price} onChange={e=>setForm({...form,whatsapp_price:e.target.value})}/></div><div><Label>WhatsApp URL (optional)</Label><Input className="mt-2" value={form.whatsapp_url} onChange={e=>setForm({...form,whatsapp_url:e.target.value})}/></div>
 <div className="md:col-span-2 rounded-lg border p-4"><div className="font-medium mb-3">Ordering Controls</div><div className="flex flex-wrap gap-6"><label className="flex items-center gap-2"><Switch checked={form.whatsapp_enabled} onCheckedChange={v=>setForm({...form,whatsapp_enabled:v})}/>WhatsApp</label><label className="flex items-center gap-2"><Switch checked={form.cod_enabled} onCheckedChange={v=>setForm({...form,cod_enabled:v})}/>COD</label><label className="flex items-center gap-2"><Switch checked={form.wholesale_enabled} onCheckedChange={v=>setForm({...form,wholesale_enabled:v})}/>Wholesale</label><label className="flex items-center gap-2"><Switch checked={form.enabled} onCheckedChange={v=>setForm({...form,enabled:v})}/>Mapping enabled</label></div></div><div className="md:col-span-2 rounded-lg border p-4"><div className="flex items-center justify-between"><div><div className="font-medium">Wholesale Tiers</div><p className="text-xs text-muted-foreground">Only used when Wholesale is enabled.</p></div><Button type="button" variant="outline" size="sm" onClick={addTier}><Plus className="mr-1 h-4 w-4"/>Add Tier</Button></div><div className="mt-3 space-y-2">{form.wholesale_pricing.map((t,i)=><div key={i} className="grid gap-2 md:grid-cols-[1fr_1fr_1fr_auto]"><Input type="number" value={t.min_quantity} onChange={e=>updateTier(i,"min_quantity",e.target.value)}/><Input type="number" value={t.max_quantity??""} onChange={e=>updateTier(i,"max_quantity",e.target.value)}/><Input type="number" value={t.unit_price} onChange={e=>updateTier(i,"unit_price",e.target.value)}/><Button type="button" variant="destructive" size="icon" onClick={()=>setForm(f=>({...f,wholesale_pricing:f.wholesale_pricing.filter((_,j)=>j!==i)}))}><Trash2 className="h-4 w-4"/></Button></div>)}</div></div><div className="md:col-span-2 flex gap-2"><Button onClick={()=>save.mutate()} disabled={save.isPending||!form.product_id||!form.whatsapp_retailer_id.trim()}>{save.isPending?"Saving...":editing?"Save Changes":"Save Product Configuration"}</Button>{editing&&<Button variant="outline" onClick={()=>{setEditing(null);setForm(empty)}}>Cancel</Button>}</div></CardContent></Card>
 <Card><CardHeader className="flex flex-row items-center justify-between gap-4"><CardTitle>All Catalog / ShoppingHub Products ({rows.length})</CardTitle><div className="relative w-full max-w-sm"><Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4"/><Input className="pl-9" placeholder="Search product or WhatsApp ID" value={search} onChange={e=>setSearch(e.target.value)}/></div></CardHeader><CardContent>{loading||mloading?<p>Loading products...</p>:<div className="space-y-3">{rows.map(p=>{const m=getMap(p);const linked=Boolean(p.whatsapp_retailer_id||p.whatsapp_catalog_id);return <div key={p.id} className="rounded-lg border bg-background p-4"><div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between"><div><div className="font-semibold">{p.name}</div><div className="text-xs text-muted-foreground mt-1">{linked?<span className="inline-flex items-center gap-1 text-green-700"><CheckCircle2 className="h-3 w-3"/>WhatsApp linked</span>:<span className="inline-flex items-center gap-1 text-amber-700"><AlertCircle className="h-3 w-3"/>WhatsApp sync pending</span>} · ID: {p.whatsapp_retailer_id||"Not assigned"}</div></div><div className="flex flex-wrap gap-2 text-xs"><span className="rounded-full border px-2 py-1">{m?"Configured":"Not configured"}</span>{m?.amazon_url&&<a className="rounded-full border px-2 py-1 inline-flex items-center gap-1" href={m.amazon_url} target="_blank" rel="noreferrer"><ExternalLink className="h-3 w-3"/>Amazon</a>}{m?.meesho_url&&<a className="rounded-full border px-2 py-1 inline-flex items-center gap-1" href={m.meesho_url} target="_blank" rel="noreferrer"><ExternalLink className="h-3 w-3"/>Meesho</a>}</div></div>{m&&<div className="mt-3 flex flex-wrap gap-2 text-xs"><span className="rounded-full border px-2 py-1">WhatsApp {m.whatsapp_enabled?(m.whatsapp_price!=null?`₹${m.whatsapp_price}`:"On"):"Off"}</span><span className="rounded-full border px-2 py-1">COD {m.cod_enabled?"On":"Off"}</span><span className="rounded-full border px-2 py-1">Wholesale {m.wholesale_enabled?"On":"Off"}</span></div>}<div className="mt-3 flex flex-wrap gap-2"><Button variant="outline" onClick={()=>edit(p,m)}><Pencil className="mr-1 h-4 w-4"/>Configure</Button>{m&&<Button variant="outline" onClick={()=>navigator.clipboard?.writeText(m.whatsapp_retailer_id).then(()=>toast({title:"WhatsApp ID copied"}))}><Copy className="mr-1 h-4 w-4"/>Copy ID</Button>}{m&&<Button variant="destructive" onClick={()=>remove.mutate(m.whatsapp_retailer_id)} disabled={remove.isPending}><Trash2 className="mr-1 h-4 w-4"/>Delete</Button>}</div></div>})}</div>}</CardContent></Card>
 </div></main></div></div></SidebarProvider>;
}
